library(lme4)
library(LoLinR)
library(png)
library(MASS)
library(RColorBrewer)
library(extrafont)
library(fontcm)
loadfonts(quiet=TRUE)

rm(list=ls())
source('paths.R')
source('R/functions-figures.R')
load('output/RDatafiles/analyses.RData')

toPdf(fig1(), 'output/figures/fig1.pdf', width=8, height=5)
embed_fonts('output/figures/fig1.pdf')
toPdf(fig2(), 'output/figures/fig2.pdf', width=8, height=7)
embed_fonts('output/figures/fig2.pdf')
