```{r, results="hide", warnings=FALSE, echo=FALSE, message=FALSE}
source('../R/functions-analyses.R')
cleanbib()
myRefs   <-  listBibs()
exporBibs(myRefs, erase=TRUE)
```
August 1, 2016

Dear Prof. Peter Raimondi,

Please find attached this resubmission version of our manuscript entitled "*Temperature effects on mass-scaling exponents in colonial animals: a manipulative test*" (original Manuscript ID: ECY16-0543) for consideration as an Article in Ecology. We would like to thank the reviewers for their insightful suggestions, most of which we have incorporated into this version of the MS, thereby increasing the clarity of the MS and the strength of its conclusions. In particular, we have improved considerably the description of our methodological set up (requested by both reviewers), and added new references and considerations regarding predation and density dependence of metabolic rates in the context of colonial organisms (requested by reviewer 2).  
Below you will find detailed responses to each one of the comments (in bold). Thank you for your consideration.

Sincerely,
Diego R. Barneche (on behalf of all coauthors) 
School of Biological Sciences 
Monash University
Melbourne, Australia 
barnechedr@gmail.com

Reviewer #1 (Comments to the Author):  
  
This study presents some interesting results on scaling of oxygen consumption with mass in 4 taxa of colonial invertebrates and the effects of temperature on the scaling relationship. The conclusions arrived at and their implications are of general interest (particularly the identification of a potential advantage of colonial over unitary animals because their predicted energy availability for growth and reproduction increases more strongly with size). However, there are many undescribed aspects of the methods and material that are likely to influence how the results are interpreted and challenge the broad conclusions of the study. These issues are currently largely overlooked by the authors. Taken to the extreme, the confounding effects of these hidden issues may entirely discredit many of the current interpretations. In addition, the ecological significance of fragmentation is not sufficiently addressed (for example by demonstrating that fragmentation frequently occurs in natural populations). Below I outline the problems.  
  
How was fragmentation of colonies done and what are the implications? Unfortunately, the reader is referred to seek details of fragmenting and tests of potential experimental artefacts as described in two studies: 1) Nakaya et al. (2015), and 2) White et al. (2011) (lines 112-114).  The former seems quite inappropriate as it is a study on an ascidian – techniques for fragmenting ascidians (which have extensive vascular connections amongst zooids) and the associated artefacts of such fragmentation will be very different than fragmenting encrusting bryozoans (and sponges and arborescent  bryozoans). White et al. (2011) worked on a different species of encrusting bryozoan than that studied by Barneche et al.  and it is not clear that fragmentation (which was presumably by cutting out circular discs from within colonies?) of one encrusting bryozoan species will entail similar artefacts in others.  Methods are meant to describe procedures so the study could be repeated but the specific details employed by Barneche et al. that would enable this to be done are almost entirely lacking. Was the sponge and arborescent bryozoan material cut in half and half again (serial fragmenting)? More generally, how many fragments were created per colony? And was the number of fragments of different sizes from different colonies always the same? If not, it would seem important to include genotype effects in all cases.  
**R: The reviewer makes a good point that not enough information was provided about the nature of fragmentation. The new version of our manuscript includes much more detail on this issue (page XX, lines XX), including a new schematic figure (new Figure 1). Briefly, for *Bugula neritina* and *Bugula stolonifera*, we reduced body size by cutting whole branches from the colony. This approach maintains the ratio of growing tips to core zooids and importantly mimics the kind of natural size reductions that *Bugula* spp. experience in the field when they are preyed upon by predatory nudibranchs `r myCite('bone2005jembe')`. For the encrusting species, we created 'pizza slice' style fragments to maintain the ratio of outer edge to inner colony as per the manipulation in White *et al.* `r myCite('white2011amnat')`. Importantly, the bryozoan used in this study has an extremely similar morphology and physiology to the one studied in White *et al.* `r myCite('white2011amnat')` so it seems that artifacts are unlikely given that White *et al.* `r myCite('white2011amnat')` comprehensively demonstrated no differences in metabolic rates between intact and experimentally fragmented colonies of similar body size. We maintained the same edge-to-inner-ratio approach by cutting pizza slices for sponges. As for the number of fragments per colony, for *Bugula* spp., this was strictly one per colony because we always cut whole branches to manipulate size, leaving the base intact. For the encrusting species, we used one to two fragments per colony and we did not record colony of origin so we cannot include genotype in our analyses. This potential caveat is now recognized in the methods (page XX, lines XX).**  
  
Nakaya et al. (2015) measured oxygen consumption in an ascidian after recovery from fragmentation (waiting for take-over to occur and a new generation of daughter zooids to replace parental generation). No such recovery was provided by Barneche et al. The lack of a recovery period may pertain to fragmentation achieved by predation or storm damage but it is unclear how biologically relevant this is. Fragmentation and survival of branches of arborescent bryozoans may occur very rarely and it seems likely that the only fragments of arborescent colonies that will remain viable in the wild are the older attached portions. How does this influence interpretation of results (see also below)? Grazing, on the other hand, may more regularly fragment encrusting colonies, and such partial predation may often leave viable portions that are still attached to the substratum. The study would benefit from an attempt to reveal the frequency and extent of such fragmentation events in natural populations of the species studied - particularly because this is the only scenario for which the results of their manipulative study can really be interpreted (see below). This would bring an ecological context to what is currently an entirely laboratory-based investigation.  
**R: As we now note point out in the methods (page XX, lines XX), our fragmentation of *Bugula* spp. mimics predation in the field -- we only used older attached portions -- so we used the most ecologically relevant fragmentation approach for arborescent bryozoans. Although we have no formal estimates of the frequency and extent of fragmentation in our encrusting study species, there is very good evidence from a range of other encrusting species that such fragmentation events are common. Also, anecdotally, we commonly observed fragments of our study species during our study, indeed, it was difficult to obtain fully intact colonies in our experience because fragmentation is always so common.**  
  
What was the life history status of the material?  The material used in the study was collected after 6 weeks in the field. By this time it seems likely that at least some if not all of the bryozoans or sponges were investing in sexual reproduction. This is a critical issue because ignoring it entails two problems for interpreting the results and their implications. First, fragments created from mature colonies that are investing in sexual reproduction may well not be equivalent to similarly-sized immature colonies that are only allocating energy to growth – nevertheless, much of the interpretations in the discussion section assume this to be the case. This means that ‘age’ potentially remains a confounding factor in the analysis, although it is claimed not to be (line 280). Second, investment in defensive polymorphs (in Bugula stolonifera and Hippopodina iririkiensis) may also increase with age and will thus entail similar problems in interpreting the results.  
**R: We focused on non-reproductive colonies to avoid the potentially complicating effects that reproduction might bring. The nature of our fragmentation approach meant that the age profile of the fragments was identical regardless of size, by cutting whole branches or pizza slices for arborescent and encrusting species respectively. As such, age is not a confounding factor in the analysis as all colonies were approximately the same age, regardless of size.**  
  
NOTE: All the bryozoans that were studied produce ovicells in which larvae are brooded and their presence would be an indication of investment in sexual reproduction. Perhaps the material was saved and could be sampled for such activity? (Allocation to defensive polymorphs could also be assessed.) Sexual activity will be harder to determine for the sponge.  
**R: We are well practiced in detecting ovicells in bryozoans and we did not use reproductive colonies (at that time of year 6 weeks was not sufficient time for colonies to show reproduction). For the sponge, we could find no evidence of reproduction, though we  cannot rule out sperm production. We now make a note of this in the manuscript (page XX, lines XX). Importantly, however, our fragmentation approach maintained identical age profiles across all fragment sizes, and therefore age is not confounding our results.**  
  
Related and other issues:  
  
White et al. (2011) found that VO2 differed between intact colonies and colony fragments. This implies that it may be inappropriate to use both whole colonies and fragments in the same experiment. However, line 124 describes measuring VO2 by placing ‘the colony or fragment’ in a glass vial. Line 139 also implies both whole colonies and fragments were used. If this is the case then the effects of fragmentation vs. no fragmentation adds an additional complexity to the study that is not addressed.  
**R: We only used fragments, the use of the term colony was an unfortunate error based on using text from the earlier paper to describe the methods. This has now been corrected throughout the methods (page XX, lines XX, page XX, lines XX). Importantly, as we point out in our methods (page XX, lines XX, page XX, lines XX, page XX, lines XX), our earlier paper `r myCite('white2011amnat')` found no difference in scaling between intact and fragments of colonies, such that our results about scaling (which is the key issue in the discussion) almost certainly apply to intact colonies of different sizes as well.**  
  
Line 130: presumably blank vials also contained no sponges?  
**R: The reviewer is correct. We have clarified this sentence replacing 'bryozoans' for 'animals' (page XX, lines XX).**  
  
Reviewer #2 (Comments to the Author):  
  
In this manuscript the authors test for interactive effects of body mass and temperature on the metabolic rates of four species of colonial marine invertebrates. By collecting individuals that colonized retrievable sheets, they were able to take apart the colonies and then reassemble them into colonies of different size, thus adding a size-manipulation component to their study. They then measured oxygen consumption and evaluated the effects of species, size, and temperature on oxygen consumption across experimental colonies.  
  
I like this study because it 1) addresses group-level metabolic rates, 2) varies colonies experimentally, 3) tests for an effect of temperature on the size scaling, 4) does so for 4 species that grow either in two or three dimensions, and 5) analyzes the data all together. It strikes me as a solid study and an interesting contribution to the metabolic ecology literature, with implications for community ecology through competitive dominance and growth.  
**R: We really appreciate the encouraging words of Dr. DeLong, and that he is appreciative of our experimental approach.**  
  
I would offer that the set-up could use a bit of clarification. The expectations for scaling slopes for different growth forms (2D versus 3D) are for individuals not colonies, so I’m not sure the expectations should really apply. You might just clarify why they still make sense anyway.  
**R: We strongly agree, and we would like to point out that we already mentioned this uncertainty regarding mass scaling exponents in colonial organisms in the introduction (page XX, lines XX): *"Currently, however, it is uncertain how colonial organisms may conform to these predictions because the original fractal geometry model considers resource-distribution networks within unitary organisms (or individual zooids) and not colonies that may (or may not) distribute resources in fundamentally different ways. Assessing the scaling of metabolic rate with body mass in colonial organisms is therefore a fundamental step in assessing how this mode of life conforms to general predictions, as well as providing an excellent opportunity for empirically manipulating mass."***  
  
Also, because the measurements deal with colonies, you might touch on the role of population size/density in setting metabolic rates, since many organisms have lower per capita metabolic rates as population density increases, including colonial organisms (DeLong et al. 2014). The sublinear scaling exponents you find provide further evidence that population size is linked to metabolic rate, because the larger colonies have more individuals. This suggests some role for intra-specific processes to influence metabolic rates. It’s not clear what those should be, but perhaps this study could suggest some possibilities.  
**R: The reviewer makes an interesting point, but there is an important difference. We now point out in the discussion (including the recommended citation) this potential role of density-dependence energetic requirements at the colony level (page XX, lines XX): "*This new predation-mediated density dependence effect will increase total population energy flux, which is opposite to what is observed in unitary organisms that form groups or colonies, where group- or population-level metabolic rates decrease often due to increasing intraspecific competition (e.g. DeLong et al. 2014). We note, however, that a ‘colony’ here is a collection of physiologically connected interdependent zooids, which is different from a colony of independent unitary individuals, hence different mechanisms are likely to be operating as density of individuals changes.*".**  
  
Should also probably mention the literature on scaling of metabolic rate in colonial insects. While not directly addressing an interaction between temperature and mass, a few papers have addressed scaling of individual and colony-level metabolic rate, with implications for competitive advantages and evolution of colonies. Check out (DeLong 2011, Shik et al. 2014).  
**R: We appreciate the suggestion. We have now incorporated DeLong 2011 in light of our findings in the discussion (page XX, lines XX).**  
  
Little things  
  
Line 55 – Should probably also mention Ginzburg and Damuth (2008) here, as they clearly raised this issue in their dimensionality paper.  
**R: Done (page XX, lines XX).**  
  
Line 69 – In this list of ecological factors should go resource supply or density dependence, which has been shown to influence metabolic rates of individuals in groups (DeLong et al. 2014). In addition, you might want to look at (Glazier et al. 2011), who found an effect of predation risk on metabolic scaling exponents for amphipods.  
**R: Both studies are now incorporated in our discussion (page XX, lines XX).**  
  
Line 227 – This might explain why group- and population-level energy use often increase with body mass, rather than showing energetic equivalence.  
**R: Point taken, and we now mention this potential in our discussion (page XX, lines XX).**  

Line 260 – Seems like the Glazier et al 2011 result may be important here, as adding predation may change the scaling slope.  
**R: The study is now incorporated in the discussion (page XX, lines XX).**  
  
Line 271 – Potentially also an effect of density here (DeLong et al. 2014).  
**R: The study is now incorporated in the discussion (page XX, lines XX).**  
  
Line 465 – I can't tell which model is bolded.  
**R: Fixed (page XX, lines XX).**  
  
Signed, John DeLong  
DeLong, J. P. 2011. Energetic inequivalence in eusocial insect colonies. Biology Letters 7:611–614.  
DeLong, J. P., T. C. Hanley, and D. A. Vasseur. 2014. Competition and the density dependence of metabolic rates. The Journal of animal ecology 83:51–58.  
Ginzburg, L., and J. Damuth. 2008. The space-lifetime hypothesis: viewing organisms in four dimensions, literally. The American Naturalist 171:125–131.  
Glazier, D. S., E. M. Butler, S. A. Lombardi, T. J. Deptola, A. J. Reese, and E. V. Satterthwaite. 2011. Ecological effects on metabolic scaling: amphipod responses to fish predators in freshwater springs. Ecological Monographs 81:599–618.  
Shik, J. Z., J. C. Santos, J. N. Seal, A. Kay, Mueller Ulrich G., and M. Kaspari. 2014. Metabolism and the rise of fungus cultivation by ants. The American Naturalist 184:364–373.  
