```{r, results="hide", warnings=FALSE, echo=FALSE, message=FALSE}
load('../output/RDatafiles/analyses.RData')
load('../output/RDatafiles/numbers.RData')
source('../R/functions-analyses.R')
source('../R/functions-figures.R')
cleanbib()
myRefs   <-  listBibs()
exporBibs(myRefs, erase=TRUE)
```
**Temperature effects on mass-scaling exponents in colonial animals: a manipulative test**  
  
*draft date: `r as.character(Sys.Date())`*  
  
Diego R. Barneche, Craig R. White, Dustin J. Marshall  

Centre for Geometric Biology / School of Biological Sciences, Monash University, Clayton, Victoria, Australia 3800  
  
**Summary**  

1. Metabolic theory posits that size and temperature are fundamental drivers of ecological patterns and processes, via their respective associations with metabolic rates. Metabolic rates are well known to increase allometrically with body mass and approximately exponentially with temperature, but most applications of metabolic theory treat these effects as independent.  
2. Almost all studies of intraspecific scaling of unitary organisms must rely on ontogenetic differences in size to examine its relationship with metabolic rate, thereby potentially confounding age, nutrition or growth rate with size –- all of which can affect metabolic rate. In the present study, we use a manipulative approach to test for an association between metabolic mass scaling and temperature dependence in four species of colonial marine invertebrates belonging to two phyla.  
3. While increased temperature increased metabolic rate, we found no consistent effect of temperature or growth form on metabolic scaling; rather the effects were species-specific. We show that mass-scaling exponents and temperature dependencies interact in ways that are unanticipated by extant theory.  
4. The allometric scaling of metabolic rate that we observe in the present study contrasts with the isometric scaling of water clearance and feeding rates observed in some colonial marine invertebrates. Our findings suggest that the often observed competitive superiority of colonial organisms over unitary ones may arise because energy availability for growth and or reproduction (the difference between energy intake and expenditure) increases more strongly with size in colonial organisms.  

**Key-words:** energetics, scaling, thermal limits, latitude, metabolic theory  
  
**Introduction**  
  
Metabolic theories seek to unite hierarchical levels of biological organisation, from individuals to ecosystems `r myCite(c('nisbet2000janimecol', 'brown2004', 'vandermeer2006tree'))`. Although definitive tests of their underlying assumptions remain rare `r myCite(c('kearney2012amnat', 'newberry2015ploscomputbiol'))`, myriad studies examined their predictions with regards to the relationship between individual level metabolic rates, $B_i$, and individual body mass, $M_i$ `r myCite(c('kleiber1932', 'kleiber1961', 'peters1983', 'schmidtnielsen1984', 'glazier2005biolrev', 'delong2010', 'glazier2010biolrev'))`. The relationship between $B_i$ and $M_i$ is typically described by a power function of the form $B_i = B_oM_i^{\alpha}$, where $B_o$ is a normalisation constant independent of mass and $\alpha$ is a dimensionless scaling exponent. Numerous studies have demonstrated that, for most animals, individual metabolic rate scales sub-linearly with body mass, with $\alpha$ estimates varying with many biotic and abiotic variables (e.g. `r myCite(c('lovegrove2000amnat', 'white2009evolution', 'killen2010ele', 'kolokotrones2010nature', 'vaca2010biollett', 'glazier2011ecolmongr', 'ketola2012jlinsoc', 'white2012procb', 'white2013jcompphysb', 'barneche2014ele'))`), generally falling between 0.5 and 1. While these studies demonstrate clearly that the value of $\alpha$ is not fixed, they each share a common limitation: each study tests for an association between $\alpha$ and a biotic or abiotic variable, using a value of $\alpha$ that is estimated from the association between $B_i$ and $M_i$ for individuals or species of different size. Such correlative studies cannot address the causal association between $B_i$ and $M_i$, because $M_i$ is correlated with a range of other environmental, physiological, and life history variables (see e.g. `r myCite(c('peters1983', 'calder1984book', 'schmidtnielsen1984'))` for comprehensive reviews) and many of these variables are also associated with $B_i$ `r myCite(c('mcnab2002book', 'konarzewski2013jcompphysb', 'white2013jcompphysb'))`.

In contrast to studies that make use of intact individual organisms, colonial animals provide an opportunity for more definitive tests of metabolic theories. Colony size can be manipulated experimentally, hence allowing for the potential to remove the confounding effects of body size and life-history traits (e.g. `r myCite('white2011amnat')`). Furthermore, different colonial species may grow in different dimensions, and the mass-scaling exponent $\alpha$ is explicitly predicted to change with number of body dimensions `r myCite(c('nakaya2005procb', 'white2011amnat', 'kearney2012amnat'))`. For example, the fractal geometry model `r myCite(c('west1997science', 'west1999science'))` predicts that $\alpha = n/(n + 1)$ for a $n$-dimensional organism, hence a value of $\alpha$ = 0.75 is predicted for three-dimensional animals while a value of $\alpha$ = 0.67 is predicted for two-dimensional animals (`r myCite(c('enquist2009nature', 'savage2008ploscompbiol', 'banavar2010pnas', 'kolokotrones2010nature', 'koontz2009amjbot'))`; but see `r myCite('price2007pnas')` for additional predictions of $\alpha$ upon modifications of canonical assumptions). Moreover, experimental size manipulation in colonial organisms allows for tests of how ecological processes such as predation or disturbance affect metabolic rates. For instance, it has been demonstrated that mimicking the effects of partial predation of physical disturbance through experimental size manipulation yields different responses in growth and reproductive onset in different species of encrusting and arborescent bryozoans `r myCite(c('bone2005jembe', 'hart2009ecologyb'))`. Yet, the metabolic consequences of these size manipulations remains unclear.  
  
Metabolic rates are influenced by temperature, typically following an exponential function `r myCite(c('gillooly2001', 'kooijman2009book'))`. Existing metabolic theories assume nevertheless different paths through which temperature affects metabolic rates. For example, the fractal geometry model `r myCite(c('west1997science', 'west1999science'))` assumes that temperature affects the metabolic normalisation only `r myCite(c('gillooly2001', 'brown2004'))`, i.e. mass-scaling and temperature dependence of metabolic rates are fundamentally independent. In contrast, the Dynamic Energy Budget (DEB) theory for metabolic organisation `r myCite('kooijman2009book')` predicts changing relationships between mass scaling and temperature dependence through the effects of temperature on assimilation, maintenance, growth, and maturation `r myCite('kooijman2009book')`. Whether temperature dependence and mass scaling interact remains a contentious issue, though recent empirical evidence indicates that they do, at least in fishes `r myCite('killen2010ele')`. Testing such interactions matters because different mass-scaling exponents under different temperatures yield different metabolic efficiencies associated with different body sizes. For example, a body size that maximizes scope for reproduction under one temperature may be suboptimal in a cooler temperature or vice versa `r myCite('sebens1987annurevecolsys')`.  
  
In the present study we experimentally manipulate size in different colonial marine organisms from two phyla (Bryozoa [Ectoprocta] and Porifera) in order to test whether the mass scaling and temperature dependence of metabolic rates interact `r myCite(c('white2011amnat', 'kearney2012amnat'))`. In doing so, we explicitly test if these interactions are general or species specific using a Bayesian model selection procedure. Finally, we discuss the relevance of our results to the life history of different species living under different environments.  
  
**Material and Methods**  
  
*1. Animal collections*  
To collect our study organisms, roughened acetate sheets secured to the underside of 6 mm thick PVC sheets suspended from floating pontoons at a depth of 1 m were deployed at Manly Boat Harbour, Queensland, Australia (27˚27' S, 153˚11' E) and checked regularly to remove fouling organisms other than our species of interest: *Bugula neritina* and *B. stolonifera* (arborescent bryozoans that have a three dimensional tree-like growth form), *Hippopodina* sp. (an encrusting bryozoan that grows mostly in two dimensions as flat disc), and an unidentified species of sponge belonging to the Microcionidae family (`r myCite('hart2009ecology')`; again a flat species that grows mostly in two dimensions) (Table 1). After 6 weeks in the field, sheets bearing colonies were returned to the University of Queensland where they were maintained in aerated seawater for up to 48 h prior to measurements. For encrusting colonies, sections of acetate bearing whole colonies were then cut from the sheets and fragmented (see e.g. `r myCite(c('nakaya2005procb', 'white2011amnat'))` for details and tests of potential experimental artefacts). Arborescent colonies were cut directly from the acetate sheets and fragmented.  
  
*2. Respiration measurements*  
Individual metabolic rates (converted to $\mu$l $\textrm{O}_\textrm{2}$ h^-1^, *n* = `r nrow(metRates)`), $B_i$, were measured as rate of oxygen consumption, $\dot{V}\textrm{O}_\textrm{2}$ of colony fragments was measured at nominal temperatures of 10 or 25 ˚C using a 144-channel PreSens Sensor Dish Reader (SDR, AS-1 Scientific, Wellington, New Zealand) according to standard techniques `r myCite(c('koster2008meps', 'lighton2008book', 'white2011amnat'))`. $\dot{V}\textrm{O}_\textrm{2}$ was measured by placing the colony or fragment in a glass vial containing 0.2$\mu$m filtered sea water and a non-consumptive $\textrm{O}_\textrm{2}$ sensor spot and calculated from the rate of change of $\textrm{O}_\textrm{2}$ saturation ($m_a$, \% h^‑1^) as:  
  
$$\dot{V}\textrm{O}_\textrm{2} = ‑1 \left(\frac{m_a – m_b}{100}\right) V~{\beta}_{\textrm{O}_\textrm{2}}$$, (1)  
  
where $m_b$ is the rate of change of $\textrm{O}_\textrm{2}$ saturation for blank vials containing no bryozoans (\% h^-1^), ${\beta}_{\textrm{O}_\textrm{2}}$ is the oxygen capacitance of air-saturated sea water at 10 ˚C (6.4 ml l^-1^) or 25 ˚C (4.74 ml l^-1^) `r myCite('cameron1986book')` and $V$ is water volume (chambers were 0.005 l in volume and water volume was calculated by subtracting the volume of acetate and animals). At least four blank vials were recorded simultaneously with each 24-well plate to account for microbial oxygen consumption and sensor spots were calibrated with air-saturated seawater (100\% A.S.) and water containing 2\% sodium sulfite (0\% A.S.). Following measurement of $\dot{V}\textrm{O}_\textrm{2}$, colonies or fragments were blotted dry and weighed to 0.1 mg (Sartorius A 200 S, Sartorius AG, Göttingen, Germany). All measurements of $\dot{V}\textrm{O}_\textrm{2}$ were made in one of four dark constant temperature cabinets, with temperatures within a run randomised among cabinets.  
  
*3. Statistical analyses*  
To test for the interacting effects of body mass and temperature on metabolic rate across species, we fitted a three-way interaction linear model using log-transformed data  
  
$$\textrm{ln}B_i \sim \textrm{ln}M_i * Temperature * Species$$, (2)  
  
where mass (mg), $\textrm{ln}M_i$, is a continuous variable, while temperature (two levels: 10 ˚C and 25 ˚C) and species (four levels corresponding to the four species) are categorical variables. With this model, we allow each species to have a different mass-scaling slope that may change with temperature; we also account for species- and temperature-specific deviations on the metabolic normalisation (i.e. statistical model). We also included date of experiment, $\Delta D$ as a random effect on the metabolic normalisation to help control for natural experimental variability. We then performed a Bayesian model selection procedure (see below) by comparing the above full model with a series of nested two- and one-way interaction models in order to formally test for mass-temperature interactions in metabolic rates among different species.  
  
All models were fitted in a Bayesian framework by calling *JAGS* version 3.4.0 from the R package *R2jags* version 0.05-03 `r myCite('r2jags')` in order to derive posterior distributions and associated 95\% credible intervals (CIs) for the fitted parameters. Random effects were assumed to be normally distributed, with means of 0. Fitted parameters were assigned priors that were vague (i.e. locally uniform over the region supported by the likelihood) `r myCite('kruschke2014book')`. The posterior distributions of model parameters were estimated using Markov chain Monte Carlo (MCMC) methods by constructing five chains of 1,000,000 steps each, including 500,000-step burn-in periods. Chains were thinned using a 250-step interval, so a total of 10,000 steps were retained to estimate posterior distributions (i.e. 5 $\times$ (1,000,000 - 500,000)/250 = 10,000). Each nested model was compared against the full model using leave-one-out cross-validation (LOO), which, similar to widely applicable information criterion (WAIC), is a fully Bayesian model selection procedure for estimating pointwise out-of-sample prediction accuracy using the log-likelihood evaluated at the posterior simulations of the parameter values `r myCite('hooten2015ecology')`. Model significance was assessed by calculating a *z*-score from the average difference $\pm$ SE between expected log pointwise predictive density of both models, and models were considered significantly different at $\alpha \le$ 0.05. Model comparison was implemented using the R package *loo* version 0.1.3 `r myCite('loo')`. All data and code necessary to reproduce this paper, its analyses, tables and figures can be obtained on GitHub https://github.com/dbarneche/MTRBrEs.  
  
**Results**  
  
Our model selection approach indicated that the three-way interaction model (equation 2) performed significantly better than all nested two- and one-way interaction models (Table 2), thus implying that different species present different interactions between mass-scaling and temperature dependence. Particularly, the best model yields no interaction between mass scaling and temperature dependence for *Bugula stolonifera* and the Microcionidae sponge (large overlap between 95\% credible intervals for the mass-scaling slopes, $\alpha$) (Figure 1). Still, while the mass-scaling slopes are statistically the same between temperatures for these species, there is evidence for higher metabolic normalisations (i.e. intercepts), $B_o$, at higher temperatures (though not statistically significant for Microcionidae). For example, metabolic rates increase `r rounded(exp(averageEstimates$lnB25[averageEstimates$species == 'Stolonifera'])/exp(averageEstimates$lnB10[averageEstimates$species == 'Stolonifera']))`-fold between 10 ˚C and 25 ˚C for *B. stolonifera*, yielding a $Q_{10}$ of `r rounded(q10andErs$q10[q10andErs$species == 'Stolonifera'])`, which is equivalent to an activation energy of `r rounded(q10andErs$er[q10andErs$species == 'Stolonifera'], 2)` eV `r myCite(c('gillooly2001','yvondurocher2012a'))`. The best model indicates that the difference in metabolic rates between 25 ˚C and 10 ˚C for *Hippopodina* sp. decreases, on average, `r rounded(tempDeltas[1,'tempDelta'])`-fold moving from `r round(exp(2))` to `r round(exp(5))` mg. For *Bugula neritina*, however, rates increase `r rounded(1/tempDeltas[3,'tempDelta'])`-fold along the same body-mass gradient.  

Average posterior estimates of mass-scaling exponents are inconsistent among the studied species and between growth forms (2D and 3D). For example, for organisms that exhibit 2D growth, *Hippopodina* sp. shows exponents that encompass both 0.67 (Fractal geometry model prediction for 2D organisms; `r myCite('koontz2009amjbot')`) and 0.75 (Fractal geometry model prediction for 3D organisms; `r myCite(c('west1997science', 'west1999science'))`) at 10 ˚C (95\% CI: `r rounded(ci95Estimates[ci95Estimates$species == 'Bryo', 's10_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Bryo', 's10_97.5'], 2)`), but that are significantly shallower than 0.75 at 25 ˚C (95\% CI: `r rounded(ci95Estimates[ci95Estimates$species == 'Bryo', 's25_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Bryo', 's25_97.5'], 2)`). Microcionidae presents exponents that only overlap 0.67 at 10 ˚C, but not at 25 ˚C (95\% CI at 10 ˚C: `r rounded(ci95Estimates[ci95Estimates$species == 'Sponge', 's10_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Sponge', 's10_97.5'], 2)`; 95\% CI at 25 ˚C: `r rounded(ci95Estimates[ci95Estimates$species == 'Sponge', 's25_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Sponge', 's25_97.5'], 2)`). On the other hand, for 3D organisms, *Bugula neritina* presents scaling exponents that overlap both 0.67 and 0.75 at 25 ˚C (95\% CI: `r rounded(ci95Estimates[ci95Estimates$species == 'Bugula', 's25_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Bugula', 's25_97.5'], 2)`), but are significantly shallower at 10 ˚C (95\% CI: `r rounded(ci95Estimates[ci95Estimates$species == 'Bugula', 's10_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Bugula', 's10_97.5'], 2)`). Finally, *Bugula stolonifera* presents values that overlap both 0.67 and 0.75 at both temperatures (95\% CI at 10 ˚C: `r rounded(ci95Estimates[ci95Estimates$species == 'Stolonifera', 's10_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Stolonifera', 's10_97.5'], 2)`; 95\% CI at 25 ˚C: `r rounded(ci95Estimates[ci95Estimates$species == 'Stolonifera', 's25_2.5'], 2)` -- `r rounded(ci95Estimates[ci95Estimates$species == 'Stolonifera', 's25_97.5'], 2)`).  
  
**Discussion**  
  
Here, we show experimentally that the mass-scaling of metabolic rates changes between two temperatures, and in different ways across different species of marine invertebrates. We build on recent empirical evidence documenting similar changes (e.g. `r myCite('killen2010ele')`), yielding further support to the need for new metabolic theories (or reformulation of current ones) that formally incorporate interactive effects between mass scaling and temperature dependence of biological rates. Our results, however, do not indicate consistent mass-temperature interactions across growth forms -- we found idiosyncratic effects of temperature on scaling exponents across closely related species with the same growth form. Possibly, another important axis involved, which has not been considered here, is the acclimation capacity of species upon acute temperature changes. Our experimental set up, however, acclimated organisms for periods (48 h) that seem to be long enough to buffer these effects `r myCite('rezende2014functecol')`.  
  
That metabolic rate scales at an exponent of less than 1 across all four species (with the exception of *Hippopodina* sp. measured at 10 ˚C) has interesting implications for our understanding of the energetics of growth for different colonial animals. For instance, evidence suggest that water clearance and feeding rates scale either isometrically or allometrically with colony size in sponges `r myCite(c('riisgard1993meps', 'kowalke2000jembe', 'mcmurray2014aquatbiol'))`, and these rates may follow the same mass scaling of metabolic rates (see e.g. `r myCite('thomassen1995meps')`). In contrast, most studies indicate that feeding rates scale isometrically or superlinearly in both encrusting and arborescent bryozoans (e.g. `r myCite(c('okamura1984jembe', 'okamura1985jembe', 'pratt2005meps'))`). Our results and those from other studies `r myCite('hartikainen2014jeb')` indicate that metabolic rates scale allometrically in arborescent 3D bryozoans. Consequently, while every unit increase in size results in proportional increase in feeding rate, every unit increase in size results in a less-than-proportional increase in metabolic rate. Thus, as colonies increase in size, their capacity to capture food increases more quickly than the rate at which energy is expended.  
  
This differential between ingestion rates and metabolic costs may explain the observed exponential growth and reproduction observed in some colonial marine invertebrates (e.g. `r myCite(c('marshall2013evolution', 'padilla1996limn', 'winston2010icb'))`) -- because the ratio of intake to expenditure increases with size, larger colonies can allocate proportionately more energy to growth and/or reproduction. In other words, for these colonial marine invertebrates, larger colonies are more efficient at allocating food intake to somatic growth and/or reproduction than smaller colonies. Isometric energy gains and allometric energy expenditure in colonial marine invertebrates may explain why they are often competitively dominant, outgrowing and excluding unitary organisms (which generally present allometric scaling of both feeding and metabolic rates, see e.g. `r myCite(c('kooijman2009book', 'kearney2012amnat'))`) in a range of systems `r myCite(c('buss1980pnas', 'buss1990tree'))`.  
  
While the mass scaling exponent was unaffected by temperature for two species (*Bugula stolonifera* and Microcionidae), it decreased and increased for one encrusting (*Hippopodina* sp.) and one arborescent species (*Bugula neritina*), respectively. These results imply that energy use may vary for the same species in different environments, possibly affecting their ultimate colonisation success and abundance. For example, the fact that *Bugula neritina* presented a shallower mass-scaling exponent at colder temperatures possibly indicates that large cold-environment individuals are more efficient in spending energy than counterparts in warm environments. On the other hand, our results indicate that *Hippopodina* sp. presents a reduction in metabolic benefits of attaining a larger size at colder temperatures. Importantly, though, we note that there are many extrinsic factors that may affect abundance and selection on body size (e.g. predation, competition). Yet, such differentials in the costs and benefits of attaining large size may help explain why some species living in cold temperatures present a slower pace of life (e.g. `r myCite('rosa2010jmba')`). Moreover, they might improve current attempts to scale up energy from individuals to higher levels of organisation (e.g. `r myCite(c('allen2005','yvondurocher2012b','barneche2014ele','barneche2016procb'))`).  
  
In the wild, partial predation and physical disturbance are common sources of partial mortality in colonial organisms `r myCite('sebens1987annurevecolsys')`. Our findings suggest that, for some species, size reductions mediated by predation or disturbance might modulate the energetic demands of individuals of similar body mass in different environments, thus affecting life-history trajectories. For instance, at 25 ˚C, a 400-gram individual of *Bugula stolonifera* will spend `r rounded(metabolicDiff$metabolicDiff[metabolicDiff$species == 'Stolonifera'], 2)`-fold more energy than a similar-sized individual at 10 ˚C. Conversely, due to the estimated positive interaction between mass-scaling and temperature, a similar-sized individual of *B. neritina* will spend `r rounded(metabolicDiff$metabolicDiff[metabolicDiff$species == 'Bugula'], 2)`-fold more energy at 25 ˚C than at 10 ˚C. These differences, for instance, may help determine which species is a better competitor in different environments, as individual metabolic rates will also affect growth rates and time of reproduction onset `r myCite(c('sebens1987annurevecolsys', 'hart2009ecologyb'))`.  
  
Here we have demonstrated that the effects of temperature interact in various ways with the mass-scaling of metabolic rates in different species of colonial marine invertebrates encompassing two distinct phyla. By adopting a size-manipulation approach, we achieved a more definitive test of mass-scaling of metabolic rates for cancelling the confounding effects of size and age, and by mimicking predation, which constitutes a fundamental ecological process in the wild. Mass-scaling exponents vary for different species, and are not consistent across growth forms nor phylogeny. Finally, our study suggests that the often observed competitive superiority of colonial organisms over unitary ones may arise because energy availability for growth and or reproduction increases more strongly with size in colonial organisms.  
  
**Acknowledgements**  

We thank M. R. Kearney for **what reason?**, field and laboratory assistants **names?**, the Australian Research Council for financial support (grants DP0987626, DP110101776, FT130101493 to C. R. White), and **whatever grants Dustin wants to add**.  
  
**Tables**  
  
*Table 1.* Mass ranges and sampling efforts for the four species of Bryozoa and Porifera experimentally manipulated in the present study at two extreme temperatures.  
  
*Table 2.* The best candidate model was chosen based on a selection procedure with nested models where non-significant fixed effects were successively removed based on leave-one-out cross-validation. Model significance was assessed by calculating a *z*-score from the average difference $\pm$ SE between expected log pointwise predictive density of both models ($\widehat{elpd_{diff}}$).  
  
**Figures**  
  
*Figure 1.* Estimates from the three-way interaction model as obtained by Bayesian methods in *JAGS*. Results for each species are represented in groups of four plots, with blue and red colours representing actual data and parameter estimates at 10 ˚C and 25 ˚C, respectively. *Top-left* and *bottom-right*: posterior probabilities of mass-scaling exponents and metabolic normalisations (respectively), with bars over curves representing 95\% credible intervals, and numbers representing average estimates. *Bottom-left*: covariance between mass-scaling exponents and metabolic normalisations for each of the 10,000 MCMC iterations (translucent circles), with overlaid density heat-map. *Top-right*: regressions of individual metabolic rate, $\textrm{ln}B_i$, as functions of individual body mass, $\textrm{ln}M_i$. Regression fits were plotted using the average from the posterior distributions. In probability posterior plots (*top-left* and *bottom-right*), smooth probability curves (*n* = 511 values) were approximated from posterior probability density curves (*n* = 512 values); differences between adjacent $x$ values (i.e. parameter estimates) were multiplied by the average of adjacent $y$ values (i.e. respective probability density values; $(x_{i+1} - x_{i}) \times ((y_{i+1} - y_{i})/2)$) thus insuring that the integral of the probability curve $\approx$ 1.  
  
**References**  
